### ISSUE TITLE
Weird shape for U+263A, white smiling face

### ISSUE THREAD

**Issue by waldyrious** [alif-type/libertinus#183]
I noticed this when visiting [the Wiktionary page for this character](https://en.wiktionary.org/wiki/%E2%98%Ba). Look at the discrepancy between the page title (which uses Linux Libertine) and the other instances of the character in that page.

☺, U+263A ("White Smiling Face") was the original smiley face encoded in Unicode. Unfortunately due to various emoji libraries choosing to use it for emojis with various features (such as blushing cheeks, closed eyes, and sometimes even an open-mouth grin), the Unicode consortium had to release a new character specifically for this expression, to ensure consistency: 🙂, U+1F642 ("Slightly Smiling Face").

In any case, the shape used in Libertinus for the original ☺ U+263A (which is also the same as from Linux Libertine) is clearly non-standard and deviating from the original intent. Here is the glyph compared to Liberation Serif:

![U+263A on Libertinus Serif and Liberation Serif](https://user-images.githubusercontent.com/478237/40316449-596563d0-5d16-11e8-81ff-915f0e5c3776.png)

(This is also the case for the frowning counterpart, ☹ U+2639 "White Frowning Face".) 

Some links for context:
- https://unicode-table.com/en/263A/
- https://emojipedia.org/white-smiling-face/
- https://en.wikipedia.org/wiki/Emoticon#Unicode

**Comment by khaledhosny** [comment]
Feel free to send a pull request.

**Comment by waldyrious** [comment]
@khaledhosny please reopen this, I've submitted #307 as a fix :)
