### ISSUE TITLE
Math font side bearing

### ISSUE THREAD

**Issue by RuixiZhang42** [alif-type/libertinus#273]
I&nbsp;complied https://github.com/alif-type/libertinus/blob/master/documentation/Math-Sample.tex with the v6.9 2019-05-27 CTAN update and noticed some side bearing issues.

### There seems to be too much white space left to the letter j

> ![issue01](https://user-images.githubusercontent.com/39968857/59132306-da033180-8942-11e9-97ce-fe6d806ed7e7.png)<br>Observed under both XeLaTeX and LuaLaTeX.

The pair `ij` does not match the pair `ii` and the result is quite uneven. Also notice the “hole” between the `\not=` and the `j`.

### Weird spacing issue in superscript and weird accent placement

> ![issue02](https://user-images.githubusercontent.com/39968857/59132711-ed62cc80-8943-11e9-8247-dfdeaea03376.png)<br>Observed under LuaLaTeX.

The right delimiter is colliding with the uppercase `I` and the `\overline{I}` looks very strange. These two issues do not appear under XeLaTeX. On another note, the problem with `j` also appears in this equation—`j\in I` skews to the right under the product sign and `_j`’s are too far away from their atom (applies to both XeLaTeX and LuaLaTeX).

**Comment by khaledhosny** [comment]
> The pair `ij` does not match the pair `ii` and the result is quite uneven. Also notice the “hole” between the `\not=` and the `j`.

The `j` has a non-negative left side bearing so it does not clash in situations like `(j)`. You can see this with other math fonts, including Computer Modern:
![image](https://user-images.githubusercontent.com/93914/59135969-4f8df280-8981-11e9-9609-6fcfe53025b5.png)

> The right delimiter is colliding with the uppercase `I` and the `\overline{I}` looks very strange. These two issues do not appear under XeLaTeX.

LuaTeX does not apply italic correction, that is a LuaTeX issue and I have no control over. There is a LuaTeX commands to control application of italic corrections that might help here, but I don’t remember them (try asking on https://tex.stackexchange.com).

> On another note, the problem with `j` also appears in this equation—`j\in I` skews to the right under the product sign and `_j`’s are too far away from their atom (applies to both XeLaTeX and LuaLaTeX).

Same reason as the other `j` issue above.

**Comment by RuixiZhang42** [comment]
@khaledhosny Thank you for the CM example! I admit I’ve glanced over the `ii` v.s. `ij` pairs in CM as they are very subtle. But MathTime Pro&nbsp;2 seems to behave better. Here is an example using the lite version:

```tex
\documentclass{article}
\usepackage[lite,subscriptcorrection]{mtpro2}
\begin{document}
$ii\enskip ij\enskip ji\enskip
a_{ii}\enskip a_{ij}\enskip a_{ji}\enskip
(i)\enskip(j)\enskip
\fboxsep-\fboxrule\fbox{$i$}\enskip\fbox{$j$}$
\showoutput
\end{document}
```

![ijpair](https://user-images.githubusercontent.com/39968857/59141990-b8c33500-8984-11e9-92bd-1a151074b3e9.png)

I&nbsp;realized that kerning is applied in math mode (thought it was disabled in math mode…), so that’s one possible solution.

The other possible solution is to create glyphs with narrower bounding boxes (which allow the strokes to stick out) and to use contextual substitution to get the current wider-bounding-box ones when combinations with brackets occur.

**Comment by khaledhosny** [comment]
Kerning in math mode with OpenType fonts do not work in XeTeX, so that is only a partial solution. Any advanced OpenType feature like contextual substitution does not work either, not even in LuaTeX (what LuaTeX do in math mode is to map a subset OpenType features to old TeX kerning and ligature mechanisms so that is very limited).

**Comment by khaledhosny** [comment]
I changed the italic j a bit to require smaller side bearing, I think this is the best compromise that works with different math engines.
