### ISSUE TITLE
Standardize shape of CYRILLIC SMALL LETTER EF

### ISSUE THREAD

**Issue by aleslavista** [alif-type/libertinus#276]
There's the need to standardize the shape of CYRILLIC SMALL LETTER EF (U+444) in the Libertinus font.
In the attached image you can see respectively the upright, semi-bold, bold, italic, italic semi-bold an italic bold glyphs. To be honest I prefer the semi-bold, italic semi-bold glyph, I feel it's more in tune with the "retro" look of the font, and I guess this used to be the standard glyph in Libertine. In any case, a choice has to be made out of consistency.
![ef](https://user-images.githubusercontent.com/33322424/64041312-74000200-cb5f-11e9-849c-24a753221d83.png)

**Comment by khaledhosny** [comment]
I was told in https://github.com/alif-type/libertinus/issues/145 that the bifurcated version is undesired, so based on that the fix here would to change the Semibold not the other fonts.

**Comment by khaledhosny** [comment]
Consistency is overrated.

**Comment by aleslavista** [comment]
Overrated??? This way the font isn't suitable for serious typesetting, you **must** choose one form or the other.

**Comment by waldyrious** [comment]
Thanks @SirPL for fixing this in #280! For convenience, here are the new shapes:

<img src="https://user-images.githubusercontent.com/11311649/65308753-060d9000-db8b-11e9-8052-9d22d4786afe.png" />

**Comment by SirPL** [comment]
@waldyrious I am glad I could help. I will check the issues closed with `wontfix` label -- maybe there's something I can help with.
@khaledhosny I think you can remove `wontfix` label from this issue :)
