### ISSUE TITLE
Provide full support for Serbian locl feature

### ISSUE THREAD

**Issue by aleslavista** [alif-type/libertinus#277]
Support for Serbian `locl` feature is patchy in the font: typesetting with standard Cyrillic glyphs is fine but the point is that as I said some glyphs are localized while others are not. So it's better to provide full support. You'll find everything you need to know in the attached .pdf.
[Localized Serbian Glyphs.pdf](https://github.com/alif-type/libertinus/files/3560997/Localized.Serbian.Glyphs.pdf)

**Comment by aleslavista** [comment]
Why?

**Comment by khaledhosny** [comment]
Please read the README file.

**Comment by aleslavista** [comment]
OK, I understand, but please reconsider your assessment of this as a **feature request**. It's actually a **bug report** because glyphs are already implemented in some cases while in others they are not. So in any case you've got to make a choice: either you remove the `locl` feature altogether or you fix it.

**Comment by khaledhosny** [comment]
I does not really matter. If you (or someone else) send a pull request I’ll review and merge as appropriate regardless what I think of this issue. Keeping it open while I don’t plan to work on it is pointless.

**Comment by aleslavista** [comment]
If it's a bug report then the README file says you're going to work on it. Well, I made the case it's a bug and not a feature request because I'm not asking you to implement something new, but rather to fix something whose implementation is botched.

**Comment by alerque** [comment]
@aleslavista Do you see anything still missing for proper Serbian support not covered in #29 (and see#394)? If so please open specific issues with what is left that needs to be done.

**Comment by aleslavista** [comment]
Hello alerque,

I've reviewed #29 and #394 and I believe they mention all that needs to be said for proper Serbian support.
