### ISSUE TITLE
Placement of combining vertical bar below (U+0329)

### ISSUE THREAD

**Issue by kopeckyf** [alif-type/libertinus#279]
The combining vertical car below (UTF-8 0329) is shifted when combined with some characters.

When the Latin lower case letter l is combined with the vertical bar below, the resulting bar is shifted a little too much to the left. It should be put in the centre of the l. 

The bug arises only in `LibertinusSerif-Bold.otf` and `LibertinusSerif-Semibold.otf`. I have not seen it when the vertical bar below is combined with any other character, and the problem does not arise in `LibertinusSerif-Regular` nor in italics.

Here's an illustration of the issue:

![grafik](https://user-images.githubusercontent.com/10461729/64342478-df782280-cfea-11e9-9bff-8090d6855c59.png)

For some glyphs that have non-zero depth, the combining vertical bar below collides with the glyph. I've seen this with the Latin lower and upper case ezh, and Latin upper case J. This bug occurs in all styles of the Libertinus family.

Here's an illustration of the issue (j and g have the desired placement):

![grafik](https://user-images.githubusercontent.com/10461729/64342408-b8b9ec00-cfea-11e9-80e7-054cfa333142.png)

I'd like to thank the developers of Libertinus for their help with the placement of the top tie bar, which was a similar issue!

**Comment by kopeckyf** [comment]
@khaledhosny As far as I can see, the issue is related to the anchor point `unten_punkt`, which is not present in Semibold lowercase l and the other glyphs. Would you like me to add the anchor and initiate a pull request for the change? Since I'm rather new to FF, I'd like to leave exporting the .otf files to you.

**Comment by khaledhosny** [comment]
Sure, please send a PR and I’ll have a look. Thanks.
