### ISSUE TITLE
Glyph-related PDF/A compliance problems with Latex Libertinus

### ISSUE THREAD

**Issue by exaexa** [alif-type/libertinus#290]
Hello!

I'm trying to produce PDF/A-compliant files using pdflatex and package pdfx. I originally ran into an interesting issue with `libertine` where typesetting an italic `p` anywhere in the document caused the PDF validation to fail; which I solved by migrating to `libertinus` (Btw thanks for maintaining libertinus!). However, the issue seems to be still present with some glyphs from LibertinusMono. In particular, veraPDF checker reports this error:

```xml
     [...]
        <details passedRules="112" failedRules="2" passedChecks="220571" failedChecks="4">
          <rule specification="ISO 19005-2:2011" clause="6.2.11.4" testNumber="2" status="failed" passedChecks="0" failedChecks="2">
            <description>Embedded fonts shall define all glyphs referenced for rendering within the conforming file. A font referenced for use solely 
			in rendering mode 3 is therefore not rendered and is thus exempt from the embedding requirement.</description>
            <object>Glyph</object>
            <test>renderingMode == 3 || isGlyphPresent == null || isGlyphPresent == true</test>
            <check status="failed">
              <context>root/document[0]/pages[47](680 0 obj PDPage)/contentStream[0](681 0 obj PDContentStream)/operators[260]/usedGlyphs[41](NGHBRG+LibertinusMono-Regular 118 0  0)</context>
            </check>
            <check status="failed">
              <context>root/document[0]/pages[47](680 0 obj PDPage)/contentStream[0](681 0 obj PDContentStream)/operators[287]/usedGlyphs[28](NGHBRG+LibertinusMono-Regular 102 0  0)</context>
            </check>
          </rule>
          <rule specification="ISO 19005-2:2011" clause="6.2.11.5" testNumber="1" status="failed" passedChecks="0" failedChecks="2">
            <description>For every font embedded in a conforming file and used for rendering, the glyph width information in the font dictionary and in the embedded 
			font program shall be consistent.</description>
            <object>Glyph</object>
            <test>renderingMode == 3 || isWidthConsistent == null || isWidthConsistent == true</test>
            <check status="failed">
              <context>root/document[0]/pages[47](680 0 obj PDPage)/contentStream[0](681 0 obj PDContentStream)/operators[260]/usedGlyphs[41](NGHBRG+LibertinusMono-Regular 118 0  0)</context>
            </check>
            <check status="failed">
              <context>root/document[0]/pages[47](680 0 obj PDPage)/contentStream[0](681 0 obj PDContentStream)/operators[287]/usedGlyphs[28](NGHBRG+LibertinusMono-Regular 102 0  0)</context>
            </check>
          </rule>
        </details>
      [...]
```

...which is the same as what previously happened with Libertine italic `p`. From the report it seems that rendering certain glyphs causes insertion of glyphs with rendering mode 3 (that means "invisible") that reference some other font, which should not be present in PDF-A because it's invisible anyway.

Although I understand this might not be a `libertinus` issue at all, just switching the font magically fixes this issue with various glyphs, so I kindof suspect there's something hidden in the font that changes LaTeX behavior and causes the issue, at least indirectly. If this is caused by something different than the font, please point me in that direction.

Also, the minimal example to reproduce is this:
```latex
\documentclass{standalone}

\usepackage[a-2u]{pdfx}
\usepackage[T1]{fontenc}
\usepackage{libertinus}

\begin{document}
\tt f
\end{document}
```

The veraPDF message is below (note that if you just replace `f` by `e`, no error is produced).
```xml
<?xml version="1.0" encoding="utf-8"?>
<report>
  <buildInformation>
    <releaseDetails id="core" version="1.12.1" buildDate="2018-05-08T18:57:00Z"></releaseDetails>
    <releaseDetails id="validation-model" version="1.12.1" buildDate="2018-05-08T20:39:00Z"></releaseDetails>
    <releaseDetails id="gui" version="1.12.1" buildDate="2018-05-08T22:06:00Z"></releaseDetails>
  </buildInformation>
  <jobs>
    <job>
      <item size="30623">
        <name>/thesis/test.pdf</name>
      </item>
      <validationReport profileName="Custom profile for Charles University, version 0.8" statement="PDF file is not compliant with Validation Profile requirements." isCompliant="false">
        <details passedRules="112" failedRules="2" passedChecks="455" failedChecks="2">
          <rule specification="ISO 19005-2:2011" clause="6.2.11.4" testNumber="2" status="failed" passedChecks="0" failedChecks="1">
            <description>Embedded fonts shall define all glyphs referenced for rendering within the conforming file. A font referenced for use solely 
			in rendering mode 3 is therefore not rendered and is thus exempt from the embedding requirement.</description>
            <object>Glyph</object>
            <test>renderingMode == 3 || isGlyphPresent == null || isGlyphPresent == true</test>
            <check status="failed">
              <context>root/document[0]/pages[0](6 0 obj PDPage)/contentStream[0](8 0 obj PDContentStream)/operators[15]/usedGlyphs[0](DKJRED+LibertinusMono-Regular 102 0  0)</context>
            </check>
          </rule>
          <rule specification="ISO 19005-2:2011" clause="6.2.11.5" testNumber="1" status="failed" passedChecks="0" failedChecks="1">
            <description>For every font embedded in a conforming file and used for rendering, the glyph width information in the font dictionary and in the embedded 
			font program shall be consistent.</description>
            <object>Glyph</object>
            <test>renderingMode == 3 || isWidthConsistent == null || isWidthConsistent == true</test>
            <check status="failed">
              <context>root/document[0]/pages[0](6 0 obj PDPage)/contentStream[0](8 0 obj PDContentStream)/operators[15]/usedGlyphs[0](DKJRED+LibertinusMono-Regular 102 0  0)</context>
            </check>
          </rule>
        </details>
      </validationReport>
      <duration start="1577739529450" finish="1577739530459">00:00:01.009</duration>
    </job>
  </jobs>
  <batchSummary totalJobs="1" failedToParse="0" encrypted="0">
    <validationReports compliant="0" nonCompliant="1" failedJobs="0">1</validationReports>
    <featureReports failedJobs="0">0</featureReports>
    <repairReports failedJobs="0">0</repairReports>
    <duration start="1577739529349" finish="1577739530501">00:00:01.152</duration>
  </batchSummary>
</report>
```

The wrapped validator I use is available from https://github.com/mff-cuni-cz/cuni-thesis-validator

Thanks for any help!

**Comment by khaledhosny** [comment]
Sorry, but I can’t make a head or tail of these errors (and ISO 19005-2:2011 spec is not freely available, so I can’t consult it as well).

Since you are using PDFTeX and Type 1 fonts (which I do not maintain), you might have a better luck contacting the authors of the relevant packages. If you can replicate the iussue with OpenType fonts and XeTeX or LuaTeX I’ll try to have a look.

**Comment by exaexa** [comment]
OK, thanks. Both XeTeX and LuaTeX fail to produce a working PDF/A for me (for a different reason though). I'll try to contact the TeX package maintainer in the meantime.

**Comment by RheumGlutinosa** [comment]
Hello, please, did you manage to find out where the problem was? I am in desperate need to submit my thesis written in RMarkdown. The protocol is giving me the exact error.
This is my YAML header:

> title: ''
> output: 
>   pdf_document:
>         latex_engine: pdflatex
>         number_sections: TRUE
> geometry: "left = 4cm, right = 2cm, top = 2cm, bottom = 2cm"
> fontsize: 11pt
> classoption: twoside
> bibliography: library.bib
> reference-section-title: References
> citation_package: biblatex
> csl: journal-of-vegetation-science.csl
> header-includes:
>   - \usepackage{float}
>   - \usepackage{sectsty}
>   - \usepackage{paralist}
>   - \usepackage{setspace}\spacing{1.5}
>   - \usepackage{fancyhdr}
>   - \usepackage{lastpage}
>   - \usepackage{dcolumn}
>   - \usepackage[nottoc, numbib]{tocbibind}
>   - \usepackage{ragged2e}
>   - \usepackage{pdflscape} # pro otaceni stranek
>   - \usepackage{graphicx} # standardní vkládání obrázků do dokumentu
>   - \usepackage{titlesec}
>   - \usepackage[utf8]{inputenc}
>   - \usepackage[a-2u]{pdfx} # pro PDF/A
>   - \usepackage[T1]{fontenc} # pro PDF/A
>   - \usepackage{lmodern} # pro PDF/A
>   - \usepackage{textcomp} # pro PDF/A
>   - \usepackage{newtxmath,newtxtext}
>   - \usepackage{filecontents}
>   - \begin{filecontents*}{\jobname.xmpdata}
>   - \Author{Barbora Lepková}
>   - \Title{Endozoochorous seed dispersal by free ranging herbivores}
>   - \Keywords{herbivory\sep seed dispersal\sep endozoochory\sep abandoned landscape\sep dry grassland\sep dung seed bank\sep disturbance\sep plant traits\sep Ellenberg Indicator Values\sep seed traits\sep seed nutrient content\sep plant frequency in the landscape\sep leaf traits\sep leaf nutrient content}
>   - \Subject{Doctoral thesis}
>   - \Publisher{Charles University}
>   - \end{filecontents*}

**Comment by exaexa** [comment]
@RheumGlutinosa If I recall correctly, one of the biggest sources of the problem were the small caps, if you use \scshape or \textsc or \sc or so anywhere, you might have luck just replacing them. If you have PDF figures (esp. from python!), convert them to high-resolution PNGs or (alchemy follows:) run them through ghostscript converter (see https://github.com/exaexa/better-mff-thesis/blob/master/pdfa.sh ).  Also, some solutions/scriptage can be copied from here https://github.com/exaexa/better-mff-thesis -- we try to keep that template 100% validated with the CUNI profile

Also consider:
- updating texlive distribution to latest version
-  compiling with `lualatex` instead of `pdflatex` -- that allows you to eradicate the [T1]{fontenc} include, which AFAIK caused some of the problem.

Good luck with the thesis! :]
