### ISSUE TITLE
times symbol

### ISSUE THREAD

**Issue by Nescio0** [alif-type/libertinus#298]
In a proper typeface, the equals, plus, minus, times, and obelus symbols all have exactly the same width and centre: =+−×÷·
In the Linux Libertine (and also in your Libertinus repository) font, the centre of the times symbol is higher than the others, but only in monospace and regular:
![LLM](https://user-images.githubusercontent.com/21634324/74751300-563d6b00-526d-11ea-9ab7-e68e95cb9953.png)
![LLR](https://user-images.githubusercontent.com/21634324/74751314-59d0f200-526d-11ea-9a4e-a6ca40d0f614.png)
Whereas its centre is correct in the Display, Italic, Bold, and Bold Italic versions:
![LLD](https://user-images.githubusercontent.com/21634324/74751341-63f2f080-526d-11ea-9c87-4b56a55cd660.png)
![LLI](https://user-images.githubusercontent.com/21634324/74751384-72410c80-526d-11ea-844b-7e66603b71ac.png)
![LLB](https://user-images.githubusercontent.com/21634324/74751391-779e5700-526d-11ea-8d30-19c06dc27f4e.png)
![LLBI](https://user-images.githubusercontent.com/21634324/74751403-7bca7480-526d-11ea-95e8-c03a130285e1.png)
As well as in their sans-serif (Biolinum) counterparts:
![LBR](https://user-images.githubusercontent.com/21634324/74751425-884ecd00-526d-11ea-8381-f2d9275dd903.png)
![LBI](https://user-images.githubusercontent.com/21634324/74751438-8b49bd80-526d-11ea-8110-aa61e2f8bf1d.png)
![LBB](https://user-images.githubusercontent.com/21634324/74751448-900e7180-526d-11ea-9682-094843466278.png)
![LBBI](https://user-images.githubusercontent.com/21634324/74751462-943a8f00-526d-11ea-8d4d-ec792d1c34f6.png)

**Comment by waldyrious** [comment]
Cross-referencing the related #272 (and, to a lesser degree, #25).
