### ISSUE TITLE
LibertinusMath: Thickness of the vertical bar does not match other delimeters

### ISSUE THREAD

**Issue by nagmat84** [alif-type/libertinus#299]
**Description**
In comparison to other types of scaled delimiters, the vertical bar appears strangely thin. I am not talking about the height (as discussed in issue #175) but about the "gauge of the line". (I do not know the correct technical term in English typography.)

**To Reproduce**
Consider the following LuaLaTeX example

    \documentclass{article}
    \usepackage{libertinus}
    
    \begin{document}
    \[
    \left\lvert
      P \left[
        b = b'
      \middle\vert
        \begin{gathered}
          g \gets G\\
          2 = 1 + 1
        \end{gathered}
      \right] \right\rvert
    \]
    \end{document}

**Expected behavior**

The thickness of the outer vertical delimiters appears to be too thin compared to the thickness of the brackets.

On top: I would expect the outer vertical delimiters  at least as high as the inner brackets (this might be related to issue #175). They are a little bit smaller but I believe this would be acceptable if they were not as thin as they are at the moment. At the moment the vertical delimiters are out-dazzled by the other deli meters.

**Screenshots**

![mwe-vertical-delims](https://user-images.githubusercontent.com/7428426/74974404-7879e900-5425-11ea-9940-37383823afd8.png)

**Comment by khaledhosny** [comment]
I think it is more of the case that the square brackets are much thicker than other math fonts. But that is how Libertine was designed I don’t think it is necessarily a bad thing, it is certainly subjective.

I added few vertical variant for the bar, so its sizes behave similar to other delimiters.
