### ISSUE TITLE
Libertinus Sans: italic lowercase m not displayed by poppler

### ISSUE THREAD

**Issue by vectro** [alif-type/libertinus#300]
STEPS TO REPRODUCE: Create a PDF document with the character U+006D LATIN SMALL LETTER M in Libertinus Sans, for example with libreoffice.

Expected behavior: The 'm' is displayed

Actual behavior: The 'm' is not displayed (but does take up space)

This same issue is discussed in this thread in the poppler forum with respect to Biolinium O, which I assume libertinus sans has inherited: https://lists.nongnu.org/archive/html/freetype-devel/2018-12/msg00063.html

There is also a bug report in the Linux Libertine bug tracker: https://sourceforge.net/p/linuxlibertine/bugs/337/

**Comment by khaledhosny** [comment]
FWIW, this is actually a FreeType bug and it got fixed (https://savannah.nongnu.org/bugs/?55414). I pushed a workaround (removing the offending contour, it was some overlap removal artifact), but I can’t actually test it.
