### ISSUE TITLE
Wrong kerning in math between w and subscript-j

### ISSUE THREAD

**Issue by nagmat84** [alif-type/libertinus#301]
**Describe the bug**

In mathematics, a base symbol w followed by a subscript j have too much space while at the same time the j and the following letter nearly collide. The overall visual appearance  looks as if the subscript j actually belonged to the following letter but not to its true base symbol.

**To Reproduce**

Compile this MWE with LuaLaTeX or XeLaTeX

    \documentclass{article}
    \usepackage{libertinus}
    \begin{document}
    \(w_j q^j\) 
    \end{document}

**Expected behavior**

The spacing between the w and the j should be smaller, the spacing between the j and the q should be bigger.

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/7428426/75698495-1cc62000-5caf-11ea-96f2-c3066177d04b.png)

**Additional context**

Also, see here: https://tex.stackexchange.com/q/530675/47156

**Comment by khaledhosny** [comment]
I improved it a bit for XeTeX already, but for LuaTeX it is still broken because LuaTeX does not apply italic correction by default (for reasons beyond me).

**Comment by nagmat84** [comment]
OK. Then, who is the correct addressee to whom I should post a bug report?

**Comment by khaledhosny** [comment]
XeTeX output:
![XeTeX output](https://user-images.githubusercontent.com/93914/75700286-7e3fbc00-5cba-11ea-9fb4-2097bd9dad56.png)

**Comment by khaledhosny** [comment]
LuaTeX developers.

**Comment by nagmat84** [comment]
Sure thing. I hoped, you had an URL or mail address of the project. I was apparently unable to find it.

**Comment by waldyrious** [comment]
Looking at the description of the mirror repository https://github.com/TeX-Live/luatex, it says:

> for issues please contact the luatex mailing list

And in the support page at [luatex.org/support.html](http://www.luatex.org/support.html) there are two mailing lists mentioned ([luatex](https://tug.org/mailman/listinfo/luatex) and [dev-luatex](https://mailman.ntg.nl/mailman/listinfo/dev-luatex)), whose archives are public and show recent activity. So I guess that's where bugs can be reported.
