### ISSUE TITLE
Small capitals with macron

### ISSUE THREAD

**Issue by CampanIgnis** [alif-type/libertinus#303]
Lower case _small capitals with macron_ of vowels are replaced by lower case _regular letters with macron_. I have tested some but not all fonts of the typeface but I assume that this applies to all fonts of Libertinus. I have not checked all diacritics but I have only found this issue with macrons. 

Therefore, I kindly would like to get my mistake pointed out or an addition of lower case small capitals to all fonts of the Libertinus typeface. 

Compile 
```
\documentclass{memoir}
\usepackage{fontspec}\setmainfont{LibertinusSerif-Regular.otf}
\usepackage{unicode-math}\setmathfont{LibertinusMath-Regular.otf}
\begin{document}
\textsc{AĀ aā EĒ eē IĪ iī OŌ oō UŪ uū} (does not work)

AĀ aā EĒ eē IĪ iī OŌ oō UŪ uū (for comparison)

\={\textsc{a}}\={\textsc{e}}\={\textsc{i}}\={\textsc{o}}\={\textsc{u}} \textsc{\=a\=e\=i\=o\=u} (does not work)

\textsc L$\bar{\textsc{u}}$\textsc t$\bar{\textsc{e}}$\textsc x (dirty math trick)

\textsc{Lutex} 
\end{document}
```
with LuaLaTeX or XeLaTeX to get
<img width="570" alt="Bildschirmfoto 2020-03-11 um 15 07 01" src="https://user-images.githubusercontent.com/62064835/76425484-fd637d00-63a9-11ea-9e42-5fecd35cc846.png">

I use TeX Live 2019 (frozen) and I have manually installed Libertinus 6.11. 

_Thank you very much for this beautiful and versatile typeface._

**Comment by Nescio0** [comment]
Try the following for comparison:
```
\documentclass{article}
\begin{document}
\begin{tabular}{ll}
\verb+\textsc{A Ā a ā}+ & \textsc{A Ā a ā} \\
\verb+\textsc{E Ē e ē}+ & \textsc{E Ē e ē} \\
\verb+\textsc{I Ī i ī}+ & \textsc{I Ī i ī} \\
\verb+\textsc{O Ō o ō}+ & \textsc{O Ō o ō} \\
\verb+\textsc{U Ū u ū}+ & \textsc{U Ū u ū} \\
\verb+\textsc{Y Ȳ y ȳ}+ & \textsc{Y Ȳ y ȳ}\\
 & \\
\verb+\={\textsc{a}}+ & \={\textsc{a}} \\
\verb+\={\textsc{e}}+ & \={\textsc{e}} \\
\verb+\={\textsc{i}}+ & \={\textsc{i}} \\
\verb+\={\textsc{o}}+ & \={\textsc{o}} \\
\verb+\={\textsc{u}}+ & \={\textsc{u}} \\
\verb+\={\textsc{y}}+ & \={\textsc{y}} \\
 & \\
\verb+\textsc{\=a}+ & \textsc{\=a} \\
\verb+\textsc{\=e}+ & \textsc{\=e} \\
\verb+\textsc{\=i}+ & \textsc{\=i} \\
\verb+\textsc{\=o}+ & \textsc{\=o} \\
\verb+\textsc{\=u}+ & \textsc{\=u} \\
\verb+\textsc{\=y}+ & \textsc{\=y} \\
\end{tabular}
\end{document}
```
output with `lualatex`: [lualatex.pdf](https://github.com/alif-type/libertinus/files/4332573/lualatex.pdf)
output with `pdflatex`: [pdflatex.pdf](https://github.com/alif-type/libertinus/files/4332555/pdflatex.pdf)
output with `xelatex`: [xelatex.pdf](https://github.com/alif-type/libertinus/files/4332557/xelatex.pdf)

**Comment by khaledhosny** [comment]
Currently smallcaps cover only a small subset of Latin glyphs, and it is quite some work to extend them. Contributions are welcome, but I won’t be able to work on it, sorry.

A workaround would be forcing the decomposed form of the characters using [CGJ](https://en.wikipedia.org/wiki/Combining_Grapheme_Joiner):
```tex
\documentclass{memoir}
\usepackage{fontspec}\setmainfont{LibertinusSerif-Regular.otf}
\usepackage{unicode-math}\setmathfont{LibertinusMath-Regular.otf}
\usepackage{newunicodechar}
\def\=#1{#1^^^34f^^^304}
\newunicodechar{ā}{\=a}
\newunicodechar{ē}{\=e}
\newunicodechar{ī}{\=i}
\newunicodechar{ō}{\=o}
\newunicodechar{ū}{\=u}
\begin{document}
\textsc{AĀ aā EĒ eē IĪ iī OŌ oō UŪ uū} (does not work)

AĀ aā EĒ eē IĪ iī OŌ oō UŪ uū (for comparison)

\={\textsc{a}}\={\textsc{e}}\={\textsc{i}}\={\textsc{o}}\={\textsc{u}} \textsc{\=a\=e\=i\=o\=u} (does not work)

\textsc L$\bar{\textsc{u}}$\textsc t$\bar{\textsc{e}}$\textsc x (dirty math trick)

\textsc{Lutex} 
\end{document}
```
<img width="538" alt="Screen Shot 2020-03-29 at 9 49 35 PM" src="https://user-images.githubusercontent.com/93914/77859039-6bf86580-7207-11ea-823a-921f88dc20c1.png">

**Comment by khaledhosny** [comment]
After posting the above comment, I realized I can do the decomposition in the font, so this is done now and the above workaround is no longer needed.
