### ISSUE TITLE
XeTeX selects bold italic in place of italic for serif font

### ISSUE THREAD

**Issue by callegar** [alif-type/libertinus#305]
There may be an issue with the fonts since XeLaTeX selects the bold italic font in place of the italic font when italic is required in regular text. Instructing font spec explicitly about what font needs to be loaded works around the issue.

This looks similar to bug #210, however it is unclear to me if the issue is with XeTeX or the font.

**Comment by khaledhosny** [comment]
Please provide an example test file showing the issue.

**Comment by callegar** [comment]
Here it is...

```Latex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{Libertinus Serif}
\begin{document}
Test \emph{test} \textit{test}.
\end{document}
```

On my system, that is Ubuntu 19.04 with *upstream* TeXLive 2019 (i.e., not the distro deb packages), regularly updated with tlmgr until the freeze preceeding the TeXLive 2020 release, this small sample file leads to the correct behavior with lualatex and incorrect behavior with xelatex. In the latter case, the two final "test" words are in bold italic.

The workaround is to explicitly specify the italic font:
```latex
\setmainfont{Libertinus Serif}[%
  ItalicFont=Libertinus Serif Italic]
```
This makes lualatex and xelatex behave consistently.

**Comment by khaledhosny** [comment]
I can’t reproduce this here, please add `\XeTeXtracingfonts 1` at the top of your TeX file, run with XeTeX and check the log to see what fonts are being loaded. Also what does `fc-match -f "%{file}\n" "Libertinus Serif:style=italic"` return?

**Comment by callegar** [comment]
This is something that I had tried already
```bash
fc-match -f "%{file}\n" "Libertinus Serif:style=italic"
/usr/local/texlive/2019/texmf-dist/fonts/opentype/public/libertinus-fonts/LibertinusSerif-Italic.otf
```
looks fine, I think.

The font tracing from xelatex is in the attached log.
[test.log](https://github.com/alif-type/libertinus/files/4365176/test.log)

**Comment by callegar** [comment]
More tests...

This has to do with the fact that on my system I also have the libertinus-type1 package, that lets libertinus be usable also with traditional engines.

Now, I guess the issue is with the type1 version of the fonts, but why is xetex using so badly the list of available fonts on the system? Why favoring type1 over opentype?

**Comment by khaledhosny** [comment]
Exposing more than one version of the same font is bad practice in general and should be avoided. It seems that you are adding TeX Live font directories to FontConfig, in this case you should exclude the Type 1 directories. May be XeTeX should be smart and non-Type 1 version when both are available, but that is something beyond my control.

**Comment by callegar** [comment]
Yet, exposing type 1 is precisely what the texlive instructions suggest. It may actually be useful if you want to use the type 1 fonts provided by texlive in non-texlive applications, say LibreOffice.

In any case, the issue is not with exposing more than one version of the same font. If I stop exposing the opentype version of Libertinus, xelatex keeps picking the wrong font exactly in the same way. Incidentally it also picks semibold in place of bolditalic.

Hence, either there is an issue with the type1 versions of Libertinus (which I believe is not maintained by you), or xetex mismanages postscript fonts...  I strongly suspect that the second one is the real problem. In fact, when the opentype texlive fonts are not exposed to the system, one has
```bash
c-match -f "%{file}\n" "Libertinus Serif:style=italic"
/usr/local/texlive/2019/texmf-dist/fonts/type1/public/libertinus-type1/LibertinusSerif-Italic.pfb
```
which seems perfectly fine.

**Comment by khaledhosny** [comment]
I maintain neither XeTeX nor the Type 1 version of the fonts.

**Comment by callegar** [comment]
I imagined that! In any case, thanks! You helped me very much in delimiting the places to look for the issue.

**Comment by wujastyk** [comment]
I created the attached fontspec config file, `LibertinusSerif.fontspec`, and placed in in `<me>/texmf/tex/latex/` (and ran `sudo mktexlsr`).  Problem solved.

```
\defaultfontfeatures[Libertinus Serif]
  {
  Extension = .otf ,
  UprightFont = LibertinusSerif-Regular,
  BoldFont = LibertinusSerif-Bold,
  ItalicFont = LibertinusSerif-Italic,
  BoldItalicFont = LibertinusSerif-BoldItalic,
  }
```
Similarly, `LibertinusSans.fontspec`:
```
\defaultfontfeatures[Libertinus Sans]
  {
  Extension = .otf ,
  UprightFont = LibertinusSans-Regular,
  BoldFont = LibertinusSans-Bold,
  ItalicFont = LibertinusSans-Italic,
  BoldItalicFont = LibertinusSans-BoldItalic
  }
```
For documentation, see the Fontspect manual, section 2.3.

**Comment by imposeren** [comment]
Just in case someone still has this issue and finds this thread: instead of creating fontspec files you can just install [libertinus-otf](https://ctan.org/pkg/libertinus-otf) package and include it in your preamble:
```
\usepackage{libertinus-otf}
```
