### ISSUE TITLE
Build time Python AttributeError

### ISSUE THREAD

**Issue by alerque** [alif-type/libertinus#308]
The new build changes with UFO workflow is awesome! Great to see this. I'll be working on something similar for [The League of Movable Type](https://www.theleagueofmoveabletype.com/)'s collection of fonts and will get some use of of the tooling. I'll be sure to contribute anything I come up with that's useful back here.

I am having a little trouble making it _work_ though ;-) On `make` I get:

```
    BUILD  LibertinusSans-Regular
Traceback (most recent call last):
  File "tools/build.py", line 279, in <module>
    main()
  File "tools/build.py", line 275, in main
    font.generate(args.output)
  File "tools/build.py", line 258, in generate
    self._make_over_under_line()
  File "tools/build.py", line 88, in _make_over_under_line
    self._draw_over_under_line(name, widths)
  File "tools/build.py", line 48, in _draw_over_under_line
    bbox = font[name].getBounds(font)
AttributeError: 'Glyph' object has no attribute 'getBounds'
make: *** [Makefile:58: build/LibertinusSans-Regular.otl.otf] Error 1
```

Any idea what that's about?

**Comment by khaledhosny** [comment]
How did you install the Python dependencies? You might have an outdated ufoLib2 version.

**Comment by khaledhosny** [comment]
These are my recommended steps for a fresh build:
```
python3 -m venv env
. env/bin/activate
pip install -r requirements.txt
make
```

**Comment by alerque** [comment]
I'm running into this setting up the Libertinus font package for Arch Linux (git version), so all the dependencies need to be themselves system packages.

I see now the ufolib2 is behind the version speced in `requirements.txt`, I'll update that. Thanks.
