### ISSUE TITLE
Greek alpha iota subscript

### ISSUE THREAD

**Issue by haly964** [alif-type/libertinus#309]
Hello. Iota subscript in writing Greek is written besides and not below when applied to alpha letter. Is this a bug ?

```
\documentclass[a4paper,12pt]{report}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[greek]{babel}
\languageattribute{greek}{ancient}

\usepackage{libertinus}

\begin{document}

ᾳ    ᾀ    ᾁ   ᾂ   ᾃ   ᾄ   ᾅ   ᾆ   ᾇ   

\end{document}
```

![image](https://user-images.githubusercontent.com/62701366/77645234-b0afa280-6f62-11ea-9f78-6e4c48282d8c.png)

**Comment by khaledhosny** [comment]
An issue with the Type 1 fonts, babel or any of the other packages. Please ask on https://tex.stackexchange.com/ or contact the package authors.

Can’t reproduce with the following file and XeTeX:
```tex
\documentclass[a4paper,12pt]{report}
\usepackage{libertinus}
\begin{document}
ᾳ    ᾀ    ᾁ   ᾂ   ᾃ   ᾄ   ᾅ   ᾆ   ᾇ
\end{document}
```
