### ISSUE TITLE
Travis-CI stopped working

### ISSUE THREAD

**Issue by khaledhosny** [alif-type/libertinus#318]
No idea what is going on, but I can’t see any of my organization on travis-ci.org any more. May be it is time to migate to GitHub actions.

**Comment by khaledhosny** [comment]
It is working actually, but no notification are shown on the repository https://travis-ci.org/github/alif-type/libertinus

**Comment by khaledhosny** [comment]
Meh.

**Comment by alerque** [comment]
This is happening because Travis is in the process of shutting down the dot-org infrastructure. You need to migrate the authentication to the dot-com namespace.
