### ISSUE TITLE
Build failure (preview file) with old mupdf-tools version

### ISSUE THREAD

**Issue by waldyrious** [alif-type/libertinus#320]
**Describe the bug**

The build process fails on older mupdf-tools versions

**Steps to reproduce**
1. Install `mupdf-tools` in the most recent Ubuntu LTS, bionic beaver (18.04):
   `sudo apt install mupdf-tools`
   → This installs version 1.12, which is what's [included in that LTS's repositories](https://packages.ubuntu.com/bionic/mupdf-tools).
2. Run `make preview.svg`

**Expected vs. actual behavior**

The build process should succeed:

    $ make preview.svg
            SVG  preview

Instead, it fails due to the `-q` option not being present:

```
$ make preview.svg
        SVG  preview
draw: unknown option -q
mudraw version 1.12.0
Usage: mudraw [options] file [pages]
	--- SNIP ---
make: *** [preview.svg] Error 1
```

**Proposed solution**

This could be fixed by either:
1. requiring the minimum version of `mupdf-tools`, which I determined to be 1.15 (by trial and error since the [release notes](https://mupdf.com/release_history.html) don't mention it), or
2. replacing `-q` with `2>/dev/null` in the [`mutool` line of the Makefile](https://github.com/alif-type/libertinus/blob/b002b70b147600481907726e5965e907895add7b/Makefile#L93) (as is already done for the `xelatex` command, by the way).

I would prefer the second solution, since Ubuntu 18.04 is a version that many people will have, as the latest Ubuntu LTS. Even 19.04 has an [older version of mupdf-tools](https://packages.ubuntu.com/disco/mupdf-tools). I've tested the Makefile edit locally and it works as expected. Let me know if that's acceptable and I'll submit a patch.

**Note:** this problem would have been caught in Travis (which [also uses the bionic LTS](
https://github.com/alif-type/libertinus/blob/b002b70b147600481907726e5965e907895add7b/.travis.yml#L1)) if all the Makefile targets were built. Would you consider also enabling this?

**Comment by khaledhosny** [comment]
This is known, I depend of a relatively new version of mutool. I try to avoid redirecting output to `/dev/null` unless absolutely necessary as it obscures real errors (like the issue you had earlier with missing `tx` that would have been more obvious if the output was not redirected).

**Comment by khaledhosny** [comment]
I don’t run this on Travis because the it has a too old mutool :)

**Comment by waldyrious** [comment]
Makes sense. I can instead update `CONTRIBUTING.md` to include the minimum required version of `mupdf-tools`.

Regarding Travis, I realized that I could also install `mupdf-tools` using [Linuxbrew](https://docs.brew.sh/Homebrew-on-Linux) in my Ubuntu machine instead of from the distro's repositories, which would provide me with the [latest version](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mupdf-tools.rb). The other dependency for the preview (`texlive-xelatex`) works with the version available in bionic, so if we do the same in the Travis script, it should be possible to run the entire make script. [Here's an example](https://gist.github.com/njlr/ac278ee448dc18002763092724d4e4d4) of using Linuxbrew on Travis. WDYT?

**Comment by khaledhosny** [comment]
I want to migrate away from Travis, see #318.
