### ISSUE TITLE
The divides character is too small, especially if used with numbers.

### ISSUE THREAD

**Issue by redtrumpet** [alif-type/libertinus#324]
I think the [divides character](https://unicode-table.com/en/2223/) (U+2223) is too small. If it is used with ordinary numbers, the numbers' height exceed the vertical bar. The same holds for [does not divide](https://unicode-table.com/en/2224/) (U+2224) and [does not divide with reversed negation slash](https://unicode-table.com/en/2AEE/) (U+2AEE). Not sure if I missed other characters with similar usage.

Example:
![Bildschirmfoto_2020-05-08_10-15-29](https://user-images.githubusercontent.com/640808/81386183-e2488b80-9114-11ea-8029-388a1bfc6e2c.png)

This is how it looks if I use the [vertical line](https://unicode-table.com/en/007C/) (U+007C):
![Bildschirmfoto_2020-05-08_10-18-40](https://user-images.githubusercontent.com/640808/81386484-56832f00-9115-11ea-8e0a-7cf12be67e17.png)

I acknowledge that this might be a question about taste, so feel free to close this issue if this works as intended.

**Comment by khaledhosny** [comment]
The fonts do not support U+2223 at all, what you are seeing is coming from a fallback font.

**Comment by khaledhosny** [comment]
The same is true for U+2224 and U+2AEE.

**Comment by khaledhosny** [comment]
Oops, wrong font.

**Comment by redtrumpet** [comment]
My examples are from the math script, but I think the glyphs are the same.
