### ISSUE TITLE
Packaging on Fedora Linux possibly incorrect 

### ISSUE THREAD

**Issue by afcowie** [alif-type/libertinus#325]
Your work to sustain the former Linux Libertine project is much appreciated, and your extension to support math properly is terrific.

I've been trying to convert to using the font on Fedora and although things worked fine for Linux Libertine I'm unable to find / load the Libertinus fonts from either XeTeX or LibreOffice etc.

The **texlive-libertinus** package makes `\usepackage{libertinus}` work but that package does not depend on **texlive-libertinus-fonts** (which should probably be properly renamed **alif-libertinus-fonts**) and does not appear to make the .otf files available to XeTeX / `fontspec`. They're not showing up in the system font directory either.

This will probably take a fair bit of work to sort out but I thought you should know you may not be getting the traction on Fedora Linux systems that you otherwise would be. If you think this needs further investigating I'm happy to help.

AfC

**Comment by alerque** [comment]
Thanks for the report. I'm pretty sure @khaledhosny who whore this does *not* maintain either the TeXLive packaging or the Fedora packages. I maintain system packages for Arch Linux, but I think we/you need to track down where to report this to the Fedora package maintainer(s) whoever they might be.

It might be good to get a list of distribution package maintainers going so we can refer these issues to the right place. Issues with the TeXLive packages crop up fairly regularly on this issue tracker and I know they don't belong here.

**Comment by khaledhosny** [comment]
As @alerque said, I don’t maintain any distribution packages, and I don’t have contact with distribution maintainers. I maintain the libertinus-fonts package in CTAN (i.e. upload new versions), but has otherwise no direct involvement with the various CTAN packages.

**Comment by fitojb** [comment]
This should be forwarded to bugzilla.redhat.com
