### ISSUE TITLE
symbol \eth already defined [pandoc]

### ISSUE THREAD

**Issue by LukasCBossert** [alif-type/libertinus#327]
> https://tex.stackexchange.com/questions/549933/symbol-eth-already-defined-when-using-libertinus-otf-and-lualatex-pandoc

Using `libertinus` as fontfamily within a yaml-header of a `.md`-file and trying to convert with pandoc (2.9.2) and the pdf-engine `lualatex` (TL 2020, LuaLaTeX 1.12.0) I get the following error-message:

```
! LaTeX Error: Command `\eth' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.240 ...mbol{\eth}            {\mathord}{AMSb}{"67}
```

**Steps to reproduce**
Take this mwe for the `.md`-file

```
---
title: Test
author: Author
date: \today
fontfamily: libertinus
---
This is a test-file. 

ÄÜÖß

1234567890
```

the command for the conversion is 

```
pandoc -s libertinus-test.md --pdf-engine=lualatex -o libertinus-test.pdf
```

I figured out that the problem is the line with the math-packages:

https://github.com/jgm/pandoc/blob/9d0506e4047f797a0672d7767830b59f1710d191/data/templates/default.latex#L100

** Note **
As soon as I change the fontfamily to `libertine` it is no problem.
But same problem also occurs with `libertinus-otf` (by HV).

**Comment by alerque** [comment]
This repository (and the maintainer of the font itself) does not maintain the CTAN packages for the LaTeX ecosystem. This appears to be a problem with the packaging in those not with the font itself. I suggest you try not loading the font package at all and just using the font directly from a normal system installed variant. Also, contact the CTAN package maintainer to report this issue.

**Comment by LukasCBossert** [comment]
thanks for the feedback - it turns out to be an error with the pandoc template.
